GROUND_STATION_LIBDIRS  = $(GROUND_STATION_PATH)/lib
GROUND_STATION_CXXFLAGS = -I$(GROUND_STATION_PATH)/include -D_REENTRANT -DQT_WEBKIT -DQT_NO_DEBUG -DQT_XML_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4 -DGUI_EXPORT= -DCORE_EXPORT=
GROUND_STATION_LDFLAGS  = -L$(GROUND_STATION_LIBDIRS) -lground_station -lQtGui -lqgis_core -lqgis_gui -lgeos -lgdal1.7.0 -lGL -lXxf86vm -lXext -lX11 -lIrrlicht -lboost_filesystem -lboost_system 
