######################################################################
# Automatically generated by qmake (2.01a) Wed Dec 21 16:03:30 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . src
INCLUDEPATH += . 
CONFIG += qt qgis
QT += xml
DEFINES += GUI_EXPORT="" CORE_EXPORT=""
LIBS += -lqgis_core -lqgis_gui -lgeos -lgdal1.7.0

# Input
SOURCES += src/main.cc \
		   src/map_stream_view.cc
