.PHONY:
all:
	make -C  demo_app/  all
	make -C  waypoint_pilot_test/  all
	make -C  cockpit_player 	 all
.PHONY:
host:
	make -C  demo_app/  all
	make -C  waypoint_pilot_test/  host
	make -C  cockpit_player/   host
.PHONY:
device:
	make -C  demo_app/  device
	make -C  waypoint_pilot_test/  device
	make -C  cockpit_player/   device
.PHONY:
clean:
	make -C  demo_app/  clean
	make -C  waypoint_pilot_test/  clean
	make -C  cockpit_player/   clean
 
