all:
	make -C  autopilot        all
	make -C  libdata_stream/  all
	make -C  simulator/       all
	make -C  stream_watch/    all
host:
	make -C  autopilot        host
	make -C  libdata_stream/  host
	make -C  simulator/       host
	make -C  stream_watch/    host
device:
	make -C  autopilot        device
	make -C  libdata_stream/  device
	make -C  simulator/       device
	make -C  stream_watch/    device
clean:
	make -C  autopilot        clean
	make -C  libdata_stream/  clean
	make -C  simulator/       clean
	make -C  stream_watch/    clean
